"use client";
import { ChangeEvent, DragEvent, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { saveBlobAs } from "./download-blob";
import { paginateBorderoRows } from "./bordero-pagination.mjs";
import { getLocalOrder, getWorkstationLabel, listLocalOrders, putLocalOrder, reserveSharedOrderNumber, uploadSharedOrder } from "./order-store";
import type { SavedOrder as Saved } from "./order-types";
type Shipment={id:string;ref:string;consignmentId:string;recipient:string;packages:number;pages:number[];confidence:"Alta"|"Da verificare"};
type Extracted=Omit<Shipment,"id"|"pages">;
let borderoFontBytes:Promise<[ArrayBuffer,ArrayBuffer]>|undefined;
function loadBorderoFontBytes(){return borderoFontBytes??=Promise.all(["/fonts/NotoSans-Regular.ttf","/fonts/NotoSans-Bold.ttf"].map(async url=>{const response=await fetch(url);if(!response.ok)throw new Error(`Font PDF non disponibile: ${url}`);return response.arrayBuffer()})) as Promise<[ArrayBuffer,ArrayBuffer]>}
const tidy=(v:string)=>v.replace(/[|_]/g," ").replace(/\s+/g," ").trim().replace(/[,:;.]$/,"");
function field(t:string,l:string,n:string[]){const s=t.replace(/\r/g,"").replace(/[\t ]+/g," "),a=l.split("").map(x=>`${x}[\\s._-]*`).join(""),b=n.map(x=>x.split("").map(y=>`${y}[\\s._-]*`).join("")).join("|");const h=s.match(new RegExp(`${a}\\s*[:#-]?\\s*([\\s\\S]{2,140}?)(?=\\n|${b}|$)`,"i"));return h?tidy(h[1]):""}
function parse(t:string):Extracted{const ref=field(t,"Ref-number",["Consignment ID","Package","To","From","Weight"]),raw=field(t,"Consignment ID",["Ref-number","Package","To","From","Weight"]),id=t.match(/\b\d{6}-\d{6}\b/)?.[0]||raw.match(/\b[A-Z0-9]{4,}(?:-[A-Z0-9]{3,})+\b/i)?.[0]||"",consignmentId=/^(?!package$|weight$)[A-Z0-9-]{6,}$/i.test(id)?id:"",recipient=field(t,"To",["Consignment ID","Ref-number","Package","From","Weight"]),m=t.match(/Package\s*[:#-]?\s*\d{1,3}\s*[/|]\s*(\d{1,3})/i)||t.match(/Pack(?:age|agc|a9e)?\s*[:#-]?\s*(\d{1,3})\s*[/|]\s*(\d{1,3})/i),packages=m?Number(m[m.length-1]):1;return{ref:ref||"RIF. NON RILEVATO",consignmentId:consignmentId||"ID DA VERIFICARE",recipient:recipient||"DESTINATARIO DA VERIFICARE",packages,confidence:ref&&consignmentId&&recipient&&m?"Alta":"Da verificare"}}
function shipmentKey(item:Pick<Shipment,"id"|"ref"|"consignmentId">,fallback:string){const ref=item.ref.toUpperCase().replace(/[^A-Z0-9]/g,"");if(ref&&ref!=="RIFNONRILEVATO")return`ref:${ref}`;const consignment=item.consignmentId.toUpperCase().replace(/[^A-Z0-9]/g,"");if(consignment&&consignment!=="IDDAVERIFICARE")return`id:${consignment}`;return`page:${fallback||item.id}`}
function formatBorderoNumber(createdAt:string,sequence:number){return`${createdAt.slice(0,10).replaceAll("-","")}-${String(sequence).padStart(3,"0")}`}
async function createBorderoPdf(rows:Shipment[],total:number,createdAt:string,sequence:number){
 const [{PDFDocument,rgb},fontkitModule,[regularBytes,boldBytes]]=await Promise.all([import("pdf-lib"),import("@pdf-lib/fontkit"),loadBorderoFontBytes()]),doc=await PDFDocument.create();doc.registerFontkit(fontkitModule.default);const regular=await doc.embedFont(regularBytes,{subset:true}),bold=await doc.embedFont(boldBytes,{subset:true}),mm=(value:number)=>value*72/25.4,m=12,w=273,number=formatBorderoNumber(createdAt,sequence),chunks=paginateBorderoRows(rows);let page=doc.addPage([mm(297),mm(210)]),y=20;
 const text=(value:string,x:number,top:number,size=8,strong=false,align:"left"|"right"|"center"="left")=>{const font=strong?bold:regular,width=font.widthOfTextAtSize(value,size),shift=align==="right"?width:align==="center"?width/2:0;page.drawText(value,{x:mm(x)-shift,y:page.getHeight()-mm(top)-size,font,size,color:rgb(.06,.09,.14)})};
 const alignedCell=(value:string,x:number,boxTop:number,boxHeight:number,size=7.5,strong=true,align:"left"|"right"|"center"="left")=>{const font=strong?bold:regular,fontHeight=font.heightAtSize(size),width=font.widthOfTextAtSize(value,size),shift=align==="right"?width:align==="center"?width/2:0;page.drawText(value,{x:mm(x)-shift,y:page.getHeight()-mm(boxTop+boxHeight)+(mm(boxHeight)-fontHeight)/2,font,size,color:rgb(.06,.09,.14)})};
 const alignedLines=(values:string[],x:number,boxTop:number,boxHeight:number,size=9)=>{const fontHeight=regular.heightAtSize(size),lineHeight=mm(3.8),blockHeight=fontHeight+(values.length-1)*lineHeight,firstBaseline=page.getHeight()-mm(boxTop+boxHeight)+(mm(boxHeight)+blockHeight)/2-fontHeight;values.forEach((value,index)=>page.drawText(value,{x:mm(x),y:firstBaseline-index*lineHeight,font:regular,size,color:rgb(.06,.09,.14)}))};
 const line=(x1:number,top1:number,x2:number,top2:number,color=.6,dashArray?:number[])=>page.drawLine({start:{x:mm(x1),y:page.getHeight()-mm(top1)},end:{x:mm(x2),y:page.getHeight()-mm(top2)},thickness:.6,color:rgb(color,color,color),dashArray});
 const fit=(value:string,maxMm:number,size:number,font=regular)=>{let result=value||"-";while(result.length>1&&font.widthOfTextAtSize(result,size)>mm(maxMm))result=result.slice(0,-2)+"…";return result};
 const wrap=(value:string,maxMm:number,size:number)=>{const words=(value||"-").split(/\s+/),lines:string[]=[];let current="";for(const word of words){const next=current?`${current} ${word}`:word;if(regular.widthOfTextAtSize(next,size)<=mm(maxMm))current=next;else{if(current)lines.push(current);current=word}}if(current)lines.push(current);return lines.slice(0,2)};
 const header=(pageIndex:number)=>{text("BORDERÒ DSV",m,14,15,true);text(`N. BORDERÒ ${number}`,m+48,14.5,8,true);text("DVG Commerce",m+w/2,14,10,true,"center");text(`DATA ${new Date(createdAt).toLocaleDateString("it-IT")}`,m+w,10,7.5,false,"right");text(`PAGINA ${pageIndex+1} / ${chunks.length}`,m+w,16,7.5,true,"right");line(m,22,m+w,22,.2);y=29};
 const head=()=>{page.drawRectangle({x:mm(m),y:page.getHeight()-mm(y+8),width:mm(w),height:mm(8),color:rgb(.96,.96,.96),borderColor:rgb(.25,.25,.25),borderWidth:.5});[["N.",m+3,"left"],["REF-NUMBER",m+17,"left"],["CONSIGNMENT ID",m+70,"left"],["DESTINATARIO",m+128,"left"],["COLLI",m+266,"right"]].forEach(([label,x,align])=>alignedCell(label as string,x as number,y,8,7.5,true,align as "left"|"right"));y+=8};
 let rowOffset=0;chunks.forEach((chunk,pageIndex)=>{if(pageIndex>0)page=doc.addPage([mm(297),mm(210)]);header(pageIndex);head();chunk.forEach((row,localIndex)=>{const index=rowOffset+localIndex,recipientLines=wrap(row.recipient,128,9);if(index%2===1)page.drawRectangle({x:mm(m),y:page.getHeight()-mm(y+10),width:mm(w),height:mm(10),color:rgb(.985,.987,.99)});line(m,y+10,m+w,y+10,.84);alignedCell(String(index+1).padStart(2,"0"),m+3,y,10,9,false);alignedCell(fit(row.ref,47,9,bold),m+17,y,10,9,true);alignedCell(fit(row.consignmentId,52,9,bold),m+70,y,10,9,true);alignedLines(recipientLines,m+128,y,10,9);alignedCell(String(row.packages),m+266,y,10,9,true,"right");y+=10});rowOffset+=chunk.length;if(pageIndex===chunks.length-1){page.drawRectangle({x:mm(m),y:page.getHeight()-mm(y+20),width:mm(w),height:mm(13),color:rgb(.975,.98,.985),borderColor:rgb(.5,.5,.5),borderWidth:.7,borderDashArray:[4,4]});alignedCell(`TOTALE SPEDIZIONI: ${rows.length}`,m+5,y+7,13,9,true);alignedCell(`TOTALE COLLI: ${total}`,m+w-5,y+7,13,9,true,"right");y=Math.max(y+24,168);[["TARGA MEZZO",0],["NOME AUTISTA",92],["FIRMA AUTISTA",184]].forEach(([label,x])=>{text(label as string,m+(x as number),y,8);line(m+(x as number),y+12,m+(x as number)+78,y+12,.5,[4,4])})}});
 const bytes=await doc.save();return new Blob([Uint8Array.from(bytes)],{type:"application/pdf"});
}
export default function Home(){const[rows,setRows]=useState<Shipment[]>([]),[fileNames,setFileNames]=useState<string[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState("Carica uno o più PDF per iniziare l’estrazione."),[drag,setDrag]=useState(false),[ready,setReady]=useState<Saved|null>(null),[previewUrl,setPreviewUrl]=useState("");const input=useRef<HTMLInputElement>(null),total=useMemo(()=>rows.reduce((s,r)=>s+r.packages,0),[rows]),reviewCount=useMemo(()=>rows.filter(r=>r.confidence!=="Alta").length,[rows]),fileLabel=fileNames.length===1?fileNames[0]:fileNames.length?`${fileNames.length} PDF importati`:"";useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)},[previewUrl]);
 useEffect(()=>{const timer=window.setTimeout(()=>{try{const stored=sessionStorage.getItem("dsv-bordero-clone");if(!stored)return;const cloned=JSON.parse(stored) as Array<{ref:string;consignmentId:string;recipient:string;packages:number}>;sessionStorage.removeItem("dsv-bordero-clone");if(!Array.isArray(cloned)||!cloned.length)return;setRows(cloned.map(row=>({id:crypto.randomUUID(),ref:String(row.ref??""),consignmentId:String(row.consignmentId??""),recipient:String(row.recipient??""),packages:Math.max(1,Number(row.packages)||1),pages:[],confidence:"Alta"})));setFileNames(["Dati recuperati dallo storico"]);setNotice(`${cloned.length} spedizioni recuperate dallo storico. Verifica i dati e genera un nuovo borderò.`)}catch{}},0);return()=>window.clearTimeout(timer)},[]);
 const save=async(meta:Saved,blob:Blob)=>{meta.rows=rows.map(r=>({ref:r.ref,consignmentId:r.consignmentId,recipient:r.recipient,packages:r.packages}));if(!meta.sequence){const existing=(await listLocalOrders()).map(item=>item.meta);meta.sequence=existing.filter(item=>item.createdAt.slice(0,10)===meta.createdAt.slice(0,10)).length+1;meta.fileName=`bordero-dsv-${meta.createdAt.slice(0,10)}-${String(meta.sequence).padStart(3,"0")}.pdf`}await putLocalOrder(meta,blob,false);try{const sharedMeta=await uploadSharedOrder({meta,blob});await putLocalOrder(sharedMeta,blob,true);return{meta:sharedMeta,shared:true}}catch{return{meta,shared:false}}};
 const process=async(files:File[])=>{const pdfFiles=files.filter(file=>file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf"));if(!pdfFiles.length){setNotice("Scegli uno o più file PDF di etichette DSV.");return}setBusy(true);setNotice(`Lettura di ${pdfFiles.length} PDF in corso…`);try{const pdfjs=await import("pdfjs-dist");pdfjs.GlobalWorkerOptions.workerSrc="/pdf.worker.min.mjs";const group=new Map<string,Shipment>();rows.forEach(row=>group.set(shipmentKey(row,row.id),{...row,pages:[...row.pages]}));let pageNumber=rows.reduce((sum,row)=>sum+row.pages.length,0),labels=0;const loaded:string[]=[],failed:string[]=[];for(const file of pdfFiles){try{const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;loaded.push(file.name);for(let p=1;p<=pdf.numPages;p++){pageNumber+=1;labels+=1;const page=await pdf.getPage(p),content=await page.getTextContent(),item=parse(content.items.map(x=>"str" in x?x.str:"").join("\n")),shipment:Shipment={...item,id:crypto.randomUUID(),pages:[pageNumber]},key=shipmentKey(shipment,`${file.name}-${p}`),old=group.get(key);if(old){old.pages.push(pageNumber);old.packages=Math.max(old.packages,item.packages,old.pages.length);if(old.consignmentId==="ID DA VERIFICARE"&&item.consignmentId!=="ID DA VERIFICARE")old.consignmentId=item.consignmentId;if(old.recipient==="DESTINATARIO DA VERIFICARE"&&item.recipient!=="DESTINATARIO DA VERIFICARE")old.recipient=item.recipient;if(old.confidence!=="Alta"&&item.confidence==="Alta")old.confidence="Alta"}else group.set(key,shipment)}}catch{failed.push(file.name)}}if(!loaded.length){setNotice("Nessuno dei PDF selezionati è leggibile. Se sono scansioni, serve prima il riconoscimento OCR.");return}const result=[...group.values()].sort((a,b)=>a.ref.localeCompare(b.ref,"it"));setRows(result);setFileNames(all=>[...all,...loaded]);setNotice(`${loaded.length} ${loaded.length===1?"PDF importato":"PDF importati"}, ${labels} etichette lette e ${result.length} spedizioni raggruppate.${failed.length?` ${failed.length} file non leggibili.`:""}`)}catch{setNotice("Non riesco a elaborare i PDF selezionati. Riprova con documenti non protetti.")}finally{setBusy(false)}};
 const change=(id:string,key:keyof Shipment,value:string)=>setRows(all=>all.map(r=>r.id===id?{...r,[key]:key==="packages"?Math.max(1,Number(value)||1):value}:r));
 const generate=async()=>{if(!rows.length)return;const createdAt=new Date().toISOString();let sequence:number,fileName:string;try{const reserved=await reserveSharedOrderNumber(createdAt);sequence=reserved.sequence;fileName=reserved.fileName}catch{const existing=(await listLocalOrders()).map(item=>item.meta).filter(item=>item.createdAt.slice(0,10)===createdAt.slice(0,10));sequence=Math.max(0,...existing.map(item=>item.sequence??0))+1;fileName=`bordero-dsv-${createdAt.slice(0,10)}-${String(sequence).padStart(3,"0")}.pdf`}const meta:Saved={id:crypto.randomUUID(),createdAt,references:rows.slice(0,3).map(r=>r.ref).join(", ")+(rows.length>3?"…":""),shipments:rows.length,packages:total,fileName,sequence,createdBy:getWorkstationLabel()},blob=await createBorderoPdf(rows,total,createdAt,sequence);try{const saved=await save(meta,blob);setPreviewUrl(URL.createObjectURL(blob));setReady(saved.meta);setNotice(saved.shared?`Borderò ${formatBorderoNumber(createdAt,sequence)} archiviato nello storico condiviso.`:"Borderò salvato localmente. La sincronizzazione verrà ritentata dallo storico.")}catch{setNotice("Impossibile archiviare il borderò localmente.")}};
 const closePreview=()=>{setReady(null);setPreviewUrl("")};
 const download=async()=>{if(!ready)return;try{const result=await saveBlobAs(async()=>(await getLocalOrder(ready.id))?.blob,ready.fileName);if(result==="cancelled")return;if(result==="missing"){setNotice("Il PDF non è più disponibile nello storico locale.");return}closePreview();setNotice("Borderò salvato.")}catch{setNotice("Non riesco a salvare il PDF. Riprova o controlla i permessi del browser.")}};
 const drop=(e:DragEvent<HTMLDivElement>)=>{e.preventDefault();setDrag(false);process(Array.from(e.dataTransfer.files))};
 return <main className="app-shell">
  <header className="app-header">
   <Link className="brand" href="/" aria-label="DSV Borderò — generazione"><strong>DSV</strong><span>Borderò</span></Link>
   <nav aria-label="Navigazione principale"><Link href="/" aria-current="page">Generazione</Link><Link href="/history">Storico</Link></nav>
  </header>

  <section className="workspace">
   <header className="workspace-head">
    <div className="workspace-title"><h1>Genera il borderò</h1><span>Importa le etichette DSV, verifica i dati estratti e crea il PDF per l’autista.</span></div>
    <ol className="workflow" aria-label="Avanzamento"><li className="current"><b>1</b><span>Importa</span></li><li className={rows.length?"current":""}><b>2</b><span>Verifica</span></li><li><b>3</b><span>Esporta</span></li></ol>
   </header>

   <section className="import-panel" aria-labelledby="import-title">
    <div className="topline"><div><h2 id="import-title">Importa etichette PDF</h2><p>Uno o più file, con una o più etichette: saranno riuniti nello stesso borderò.</p></div>{fileLabel&&<span className="file-name" title={fileNames.join(", ")}>{fileLabel}</span>}</div>
    <div className={`dropzone ${drag?"active":""} ${busy?"loading":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={drop} onClick={()=>!busy&&input.current?.click()} onKeyDown={e=>{if(!busy&&(e.key==="Enter"||e.key===" ")){e.preventDefault();input.current?.click()}}} role="button" tabIndex={0} aria-busy={busy} aria-describedby="upload-help">
     <input className="visually-hidden" ref={input} id="pdf-upload" type="file" accept="application/pdf,.pdf" multiple onChange={(e:ChangeEvent<HTMLInputElement>)=>{process(Array.from(e.target.files??[]));e.target.value=""}}/>
     <div className="file-mark" aria-hidden="true">PDF</div>
     <div className="drop-copy"><strong>{busy?"Lettura dei documenti in corso…":fileLabel||"Trascina qui uno o più PDF DSV"}</strong><small id="upload-help">{busy?"Tutte le pagine vengono analizzate e raggruppate":fileNames.length?"Seleziona altri PDF da aggiungere allo stesso borderò":"oppure seleziona più file dal computer"}</small></div>
     <button type="button" disabled={busy} onClick={e=>{e.stopPropagation();input.current?.click()}}>{fileNames.length?"Aggiungi PDF":"Scegli PDF"}</button>
    </div>
    <div className="notice" role="status" aria-live="polite"><span className={reviewCount?"status-dot warning":"status-dot"}/><span>{notice}</span></div>
   </section>

   {rows.length>0?<section className="results" aria-labelledby="results-title">
    <div className="result-head"><div><h2 id="results-title">Verifica le spedizioni</h2><p>Correggi direttamente i campi prima di generare il documento.</p></div><dl className="summary"><div><dt>Spedizioni</dt><dd>{rows.length}</dd></div><div><dt>Colli</dt><dd>{total}</dd></div><div className={reviewCount?"needs-review":""}><dt>Da verificare</dt><dd>{reviewCount}</dd></div></dl></div>
    <div className="table-wrap"><table><thead><tr><th>Stato</th><th>Ref-number</th><th>Consignment ID</th><th>Destinatario</th><th>Colli</th><th>Etichette</th><th><span className="visually-hidden">Azioni</span></th></tr></thead><tbody>{rows.map((r,index)=><tr key={r.id} className={r.confidence==="Alta"?"":"review-row"}><td data-label="Stato"><span className={`badge ${r.confidence==="Alta"?"ok":"check"}`}><span aria-hidden="true">{r.confidence==="Alta"?"✓":"!"}</span>{r.confidence}</span></td><td data-label="Ref-number"><input aria-label={`Ref-number riga ${index+1}`} value={r.ref} onChange={e=>change(r.id,"ref",e.target.value)}/></td><td data-label="Consignment ID"><input className="mono-input" aria-label={`Consignment ID riga ${index+1}`} value={r.consignmentId} onChange={e=>change(r.id,"consignmentId",e.target.value)}/></td><td data-label="Destinatario"><input aria-label={`Destinatario riga ${index+1}`} value={r.recipient} onChange={e=>change(r.id,"recipient",e.target.value)}/></td><td data-label="Colli"><input aria-label={`Colli riga ${index+1}`} className="package" type="number" min="1" value={r.packages} onChange={e=>change(r.id,"packages",e.target.value)}/></td><td data-label="Etichette" className="pages">{r.pages.length}</td><td className="row-action"><button className="delete" aria-label={`Rimuovi la riga ${index+1}`} title="Rimuovi riga" onClick={()=>setRows(all=>all.filter(x=>x.id!==r.id))}>×</button></td></tr>)}</tbody></table></div>
    <div className="actions"><button className="secondary" onClick={()=>setRows(all=>[...all,{id:crypto.randomUUID(),ref:"",consignmentId:"",recipient:"",packages:1,pages:[],confidence:"Da verificare"}])}>Aggiungi riga</button><div className="action-primary"><span>{reviewCount?`${reviewCount} ${reviewCount===1?"riga da controllare":"righe da controllare"}`:"Dati pronti per l’esportazione"}</span><button className="primary" onClick={generate}>Genera borderò <span aria-hidden="true">→</span></button></div></div>
   </section>:<aside className="empty-guide"><strong>Il flusso in tre passaggi</strong><p>Carica il PDF, controlla solo le righe segnalate e genera il borderò pronto per la firma.</p></aside>}
  </section>

  {ready&&previewUrl&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closePreview()}}><section className="download-modal preview-modal" role="dialog" aria-modal="true" aria-labelledby="ready-title" aria-describedby="ready-description"><button className="modal-close" aria-label="Chiudi finestra" onClick={closePreview}>×</button><div className="modal-intro"><span className="success-mark" aria-hidden="true">✓</span><div><h2 id="ready-title">Borderò pronto</h2><p id="ready-description">Controlla l’anteprima, quindi salva il documento sul dispositivo.</p></div></div><div className="ready-layout"><div className="pdf-preview"><iframe title="Anteprima del borderò PDF" src={`${previewUrl}#toolbar=0&navpanes=0&view=FitH`}/><p>Anteprima non visibile? <a href={previewUrl} target="_blank" rel="noreferrer">Apri il PDF in una nuova scheda</a>.</p></div><aside className="ready-details"><dl className="modal-summary"><div><dt>Numero borderò</dt><dd>{formatBorderoNumber(ready.createdAt,ready.sequence??1)}</dd></div><div><dt>Spedizioni</dt><dd>{ready.shipments}</dd></div><div><dt>Colli</dt><dd>{ready.packages}</dd></div><div><dt>Creato</dt><dd>{new Date(ready.createdAt).toLocaleString("it-IT")}</dd></div></dl><div className="modal-actions"><button className="secondary" onClick={closePreview}>Chiudi</button><button className="primary" onClick={download}>Salva PDF</button></div></aside></div></section></div>}
 </main>}
